[[item]]
file = "~/.config/alacritty/themes/base16.yml"
template = "alacritty"
# subtemplate = "default-256"
hook = "touch ~/.config/alacritty/alacritty.yml"
rewrite = true

[[item]]
file = "~/.config/btop/themes/base16.theme"
template = "btop"
rewrite = true

[[item]]
file = "~/.config/doom/themes/base16-theme.el"
template = "doom"
rewrite = true

[[item]]
file = "~/.config/i3lock/i3lock.sh"
template = "dmlock"
rewrite = false

[[item]]
file = "~/.config/trayer/trayer.sh"
template = "trayer"
# hook = "~/.config/trayer/trayer.sh"
light = false
rewrite = false

[[item]]
file = "~/.config/dunst/dunstrc"
template = "dunst"
subtemplate = "custom"
hook = "killall dunst"
rewrite = false

[[item]]
file = "~/.config/eww/themes/base16.scss"
template = "eww"
subtemplate = "default"
light = true
rewrite = true

[[item]]
file = "~/.config/mpv/script-opts/torque-progressbar/main.conf"
template = "mpv"
subtemplate = "torque-progressbar"
rewrite = false

[[item]]
file = "~/.config/gtk-2.0/gtkrc"
template = "gtk-flatcolor"
subtemplate = "gtk-2"
# template = "gtk2"
# subtemplate = "schemes"
rewrite = false

[[item]]
file = "~/.config/gtk-3.0/gtk.css"
template = "gtk-flatcolor"
subtemplate = "gtk-3"
rewrite = false
start = "/* Start flavours */"
end = "/* End flavours */"

[[item]]
file = "~/.config/qtile/themes/base16.py"
template = "qtile"
hook = "qtile cmd-obj -o cmd -f restart"
light = false
rewrite = true

[[item]]
file = "~/.config/qutebrowser/themes/base16.py"
template = "qutebrowser"
subtemplate = "custom"
hook = "pgrep -x qutebrowser && qutebrowser :config-source"
light = false
rewrite = true

[[item]]
file = "~/.config/rofi/themes/base16.rasi"
template = "rofi"
subtemplate = "colors"
rewrite = true

[[item]]
file = "~/.termux/termux.properties"
template = "termux"
# subtemplate = "default-256"
rewrite = false

[[item]]
file = "~/.config/vimiv/styles/base16.conf"
template = "vimiv"
start = "; Start flavours"
end = "; End flavours"

[[item]]
file = "~/.config/xmobar/mainScreen.hs"
template = "xmobar"
start = "-- Start flavours"
end = "-- End flavours"

[[item]]
file = "~/.config/xmobar/secondaryScreen.hs"
template = "xmobar"
start = "-- Start flavours"
end = "-- End flavours"

[[item]]
file = "~/.config/xmonad/lib/Themes/Base16.hs"
template = "xmonad"
hook = "xmonad --restart"
light = false
rewrite = true

[[item]]
file = "~/.config/X11/Xresources"
template = "xresources"
# subtemplate = "default-256"
start = "! Start flavours"
end = "! End flavours"

[[item]]
file = "~/.config/zathura/themes/base16"
template = "zathura"
subtemplate = "recolor"
rewrite = true
